version: "3.9"  # Try this compose file for local-dev setup
services:
  bt1-node:
    image: klayoracle-node:v1.0.2-beta
    container_name: bootstrap_node1
    ports:
      - "50051:50051"
    volumes:
      - ./setup-guide/volumes/nodes/nd1/host/x509:/var/klayoracle/certs/host/x509
      - ./setup-guide/volumes/nodes/nd1/config.yaml:/var/klayoracle/config.yaml
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/nodes/nd1/.env
    restart: unless-stopped
  bt2-node:
    image: klayoracle-node:v1.0.2-beta
    container_name: bootstrap_node2
    ports:
      - "50052:50051"
    depends_on:
      - bt1-node
    volumes:
      - ./setup-guide/volumes/nodes/nd2/host/x509:/var/klayoracle/certs/host/x509
      - ./setup-guide/volumes/nodes/nd2/config.yaml:/var/klayoracle/config.yaml
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/nodes/nd2/.env
    restart: unless-stopped
  bt3-node:
    image: klayoracle-node:v1.0.2-beta
    container_name: bootstrap_node3
    ports:
      - "50053:50051"
    depends_on:
      - bt2-node
    volumes:
      - ./setup-guide/volumes/nodes/nd3/host/x509:/var/klayoracle/certs/host/x509
      - ./setup-guide/volumes/nodes/nd3/config.yaml:/var/klayoracle/config.yaml
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/nodes/nd3/.env
    restart: unless-stopped
  bt4-node:
    image: klayoracle-node:v1.0.2-beta
    container_name: bootstrap_node4
    ports:
      - "50054:50051"
    depends_on:
      - bt3-node
    volumes:
      - ./setup-guide/volumes/nodes/nd4/host/x509:/var/klayoracle/certs/host/x509
      - ./setup-guide/volumes/nodes/nd4/config.yaml:/var/klayoracle/config.yaml
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/nodes/nd4/.env
    restart: unless-stopped
  bt5-node:
    image: klayoracle-node:v1.0.2-beta
    container_name: bootstrap_node5
    ports:
      - "50055:50051"
    depends_on:
      - bt4-node
    volumes:
      - ./setup-guide/volumes/nodes/nd5/host/x509:/var/klayoracle/certs/host/x509
      - ./setup-guide/volumes/nodes/nd5/config.yaml:/var/klayoracle/config.yaml
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/nodes/nd5/.env
    restart: unless-stopped
  bt1-dp:
    image: klayoracle-dp:v1.0.2-beta
    container_name: bootstrap_dp1
    depends_on:
      - bt1-node
    ports:
      - "50002:50002"
    volumes:
      - ./setup-guide/volumes/dps/dp1/node/x509:/var/klayoracle/certs/node/x509
      - ./setup-guide/volumes/dps/dp1/config.yaml:/var/klayoracle/config.yaml
      - ./setup-guide/volumes/dps/dp1/feeds:/var/klayoracle/feeds
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/dps/dp1/.env
    restart: unless-stopped
  bt2-dp:
    image: klayoracle-dp:v1.0.2-beta
    container_name: bootstrap_dp2
    ports:
      - "50003:50002"
    depends_on:
      - bt2-node
      - bt1-dp
    volumes:
      - ./setup-guide/volumes/dps/dp2/node/x509:/var/klayoracle/certs/node/x509
      - ./setup-guide/volumes/dps/dp2/config.yaml:/var/klayoracle/config.yaml
      - ./setup-guide/volumes/dps/dp2/feeds:/var/klayoracle/feeds
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/dps/dp2/.env
    restart: unless-stopped
  bt3-dp:
    image: klayoracle-dp:v1.0.2-beta
    container_name: bootstrap_dp3
    ports:
      - "50004:50002"
    depends_on:
      - bt3-node
      - bt2-dp
    volumes:
      - ./setup-guide/volumes/dps/dp3/node/x509:/var/klayoracle/certs/node/x509
      - ./setup-guide/volumes/dps/dp3/config.yaml:/var/klayoracle/config.yaml
      - ./setup-guide/volumes/dps/dp3/feeds:/var/klayoracle/feeds
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/dps/dp3/.env
    restart: unless-stopped
  bt4-dp:
    image: klayoracle-dp:v1.0.2-beta
    container_name: bootstrap_dp4
    ports:
      - "50005:50002"
    depends_on:
      - bt4-node
      - bt3-dp
    volumes:
      - ./setup-guide/volumes/dps/dp4/node/x509:/var/klayoracle/certs/node/x509
      - ./setup-guide/volumes/dps/dp4/config.yaml:/var/klayoracle/config.yaml
      - ./setup-guide/volumes/dps/dp4/feeds:/var/klayoracle/feeds
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/dps/dp4/.env
    restart: unless-stopped
  bt5-dp:
    image: klayoracle-dp:v1.0.2-beta
    container_name: bootstrap_dp5
    ports:
      - "50006:50002"
    depends_on:
      - bt5-node
      - bt4-dp
    volumes:
      - ./setup-guide/volumes/dps/dp5/node/x509:/var/klayoracle/certs/node/x509
      - ./setup-guide/volumes/dps/dp5/config.yaml:/var/klayoracle/config.yaml
      - ./setup-guide/volumes/dps/dp5/feeds:/var/klayoracle/feeds
    networks:
      - klayoracle
    env_file:
      - setup-guide/volumes/dps/dp5/.env
    restart: unless-stopped
networks:
  klayoracle:
    external: true