// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: node/protonode/node.proto

package protonode

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	HandShake(ctx context.Context, in *DPInfo, opts ...grpc.CallOption) (*HandShakeStatus, error)
	QueueJob(ctx context.Context, opts ...grpc.CallOption) (NodeService_QueueJobClient, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) HandShake(ctx context.Context, in *DPInfo, opts ...grpc.CallOption) (*HandShakeStatus, error) {
	out := new(HandShakeStatus)
	err := c.cc.Invoke(ctx, "/protonode.NodeService/HandShake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) QueueJob(ctx context.Context, opts ...grpc.CallOption) (NodeService_QueueJobClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], "/protonode.NodeService/QueueJob", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeServiceQueueJobClient{stream}
	return x, nil
}

type NodeService_QueueJobClient interface {
	Send(*Adapter) error
	Recv() (*OracleRequest, error)
	grpc.ClientStream
}

type nodeServiceQueueJobClient struct {
	grpc.ClientStream
}

func (x *nodeServiceQueueJobClient) Send(m *Adapter) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeServiceQueueJobClient) Recv() (*OracleRequest, error) {
	m := new(OracleRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	HandShake(context.Context, *DPInfo) (*HandShakeStatus, error)
	QueueJob(NodeService_QueueJobServer) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) HandShake(context.Context, *DPInfo) (*HandShakeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandShake not implemented")
}
func (UnimplementedNodeServiceServer) QueueJob(NodeService_QueueJobServer) error {
	return status.Errorf(codes.Unimplemented, "method QueueJob not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_HandShake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HandShake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protonode.NodeService/HandShake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HandShake(ctx, req.(*DPInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_QueueJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).QueueJob(&nodeServiceQueueJobServer{stream})
}

type NodeService_QueueJobServer interface {
	Send(*OracleRequest) error
	Recv() (*Adapter, error)
	grpc.ServerStream
}

type nodeServiceQueueJobServer struct {
	grpc.ServerStream
}

func (x *nodeServiceQueueJobServer) Send(m *OracleRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeServiceQueueJobServer) Recv() (*Adapter, error) {
	m := new(Adapter)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protonode.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandShake",
			Handler:    _NodeService_HandShake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueueJob",
			Handler:       _NodeService_QueueJob_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node/protonode/node.proto",
}
