kind: ConfigMap
apiVersion: v1
metadata:
  name: 
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    env: stage #options: dev, stage, production
    organization:
      k_org_id: 535797165684
      name: KlayOracle Inc. ${POD_NAME}
      website: "node-1.origineum.com"
    ssl:
      key: "x509/origineum_node_key.pem"
      certificate: "x509/origineum_node_cert.pem"
  