{{- $fullName := include "node.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-certs
  labels:
    ßapp: {{ $fullName }}
    chart: {{ $fullName }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ ( include "node.gen-certs" . ) | indent 2 }}