apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "node.fullname" . }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OAUTH_TOKEN
              value: {{ .Values.env.oauthToken }}
            - name: HOST_IP
              value: {{ .Values.env.hostIP }}
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: {{ .Values.env.grpcGoLogVerbosityLevel | quote }}
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: {{ .Values.env.grpcGoLogSeverityLevel }}
            - name: COCKROACH_DNS_URL
              value: {{ .Values.env.cockroachDnsUrl }}
            - name: PRIVATE_KEY
              value: {{ .Values.env.privateKey }}
            - name: PUBLIC_ADDRESS
              value: {{ .Values.env.publicAddress }}
            - name: NODE_URL
              value: {{ .Values.env.nodeUrl }}
            - name: NODE_URL_HTTPS
              value: {{ .Values.env.nodeUrlHttps }}
            - name: environment
              value: {{ .Values.env.runtime }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
