env: stage #options: dev, stage, production
organization:
  k_org_id: 535797165685
  name: "KlayOracle Inc. bt-node-2"
  website: "node-2.origineum.com"
ssl:
  key: "x509/origineum_node_key.pem"
  certificate: "x509/origineum_node_cert.pem"