env: dev #options: dev, stage, production
service_node: bootstrap_node3:50051
feed:
  path: "feeds"
  adapters:
    - ETH_USD.json
    - GOOG_USD.json
    - GOOGL_USD.json
    - JPM_USD.json
organization:
  k_org_id: 535797165696
  name: "KlayOracle Inc."
  website: "dp-3.klayoracle.com"
ssl:
  key: ""
  certificate: "x509/535797165686.pem"
