env: dev #options: dev, stage, production
service_node: localhost:50051
feed:
  path: "feeds"
  adapters:
    - KLAY_USD.json
    - RANDOM.json
organization:
  k_org_id: 535797165684
  name: "KlayOracle Inc."
  website: "dp-1.origineum.com"
ssl:
  key: ""
  certificate: "x509/535797165684.pem"
