env: dev #options: dev, stage, production
service_node: localhost:50051
feed:
  path: "feeds"
  adapters:
    - KLAY_USD.json
    - RANDOM.json
organization:
  k_org_id: "XX-XXX-804-23"
  name: "KlayOracle Inc."
  website: "x.test.example.com"
ssl:
  key: ""
  certificate: "x509/ca_cert.pem"
