// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: data-provider/protoadapter/adapter.proto

package protoadapter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataProviderClient is the client API for DataProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataProviderClient interface {
	// Server streaming RPC
	// Node as client sends request using Stub to Data Provider as Server
	// Gets a continuous unending stream to notify Node of connection
	Ping(ctx context.Context, in *Node, opts ...grpc.CallOption) (DataProvider_PingClient, error)
	// Unary RPC
	// Node as client sends request to retrieve details of an Adapter
	// Waits and gets a one time response and connection is closed
	GetAdapter(ctx context.Context, in *AdapterHead, opts ...grpc.CallOption) (*Adapter, error)
	// Server streaming RPC
	// Node as client requests for Adapter lists from Data Providers as Server
	// Data Providers sends a stream of all available adapter and closes connection after sending the last one
	ListAdapters(ctx context.Context, in *Node, opts ...grpc.CallOption) (DataProvider_ListAdaptersClient, error)
}

type dataProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewDataProviderClient(cc grpc.ClientConnInterface) DataProviderClient {
	return &dataProviderClient{cc}
}

func (c *dataProviderClient) Ping(ctx context.Context, in *Node, opts ...grpc.CallOption) (DataProvider_PingClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataProvider_ServiceDesc.Streams[0], "/protoadapter.DataProvider/Ping", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataProviderPingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataProvider_PingClient interface {
	Recv() (*ServerStatus, error)
	grpc.ClientStream
}

type dataProviderPingClient struct {
	grpc.ClientStream
}

func (x *dataProviderPingClient) Recv() (*ServerStatus, error) {
	m := new(ServerStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataProviderClient) GetAdapter(ctx context.Context, in *AdapterHead, opts ...grpc.CallOption) (*Adapter, error) {
	out := new(Adapter)
	err := c.cc.Invoke(ctx, "/protoadapter.DataProvider/GetAdapter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataProviderClient) ListAdapters(ctx context.Context, in *Node, opts ...grpc.CallOption) (DataProvider_ListAdaptersClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataProvider_ServiceDesc.Streams[1], "/protoadapter.DataProvider/ListAdapters", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataProviderListAdaptersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataProvider_ListAdaptersClient interface {
	Recv() (*Adapter, error)
	grpc.ClientStream
}

type dataProviderListAdaptersClient struct {
	grpc.ClientStream
}

func (x *dataProviderListAdaptersClient) Recv() (*Adapter, error) {
	m := new(Adapter)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataProviderServer is the server API for DataProvider service.
// All implementations must embed UnimplementedDataProviderServer
// for forward compatibility
type DataProviderServer interface {
	// Server streaming RPC
	// Node as client sends request using Stub to Data Provider as Server
	// Gets a continuous unending stream to notify Node of connection
	Ping(*Node, DataProvider_PingServer) error
	// Unary RPC
	// Node as client sends request to retrieve details of an Adapter
	// Waits and gets a one time response and connection is closed
	GetAdapter(context.Context, *AdapterHead) (*Adapter, error)
	// Server streaming RPC
	// Node as client requests for Adapter lists from Data Providers as Server
	// Data Providers sends a stream of all available adapter and closes connection after sending the last one
	ListAdapters(*Node, DataProvider_ListAdaptersServer) error
	mustEmbedUnimplementedDataProviderServer()
}

// UnimplementedDataProviderServer must be embedded to have forward compatible implementations.
type UnimplementedDataProviderServer struct {
}

func (UnimplementedDataProviderServer) Ping(*Node, DataProvider_PingServer) error {
	return status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDataProviderServer) GetAdapter(context.Context, *AdapterHead) (*Adapter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdapter not implemented")
}
func (UnimplementedDataProviderServer) ListAdapters(*Node, DataProvider_ListAdaptersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAdapters not implemented")
}
func (UnimplementedDataProviderServer) mustEmbedUnimplementedDataProviderServer() {}

// UnsafeDataProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataProviderServer will
// result in compilation errors.
type UnsafeDataProviderServer interface {
	mustEmbedUnimplementedDataProviderServer()
}

func RegisterDataProviderServer(s grpc.ServiceRegistrar, srv DataProviderServer) {
	s.RegisterService(&DataProvider_ServiceDesc, srv)
}

func _DataProvider_Ping_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Node)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataProviderServer).Ping(m, &dataProviderPingServer{stream})
}

type DataProvider_PingServer interface {
	Send(*ServerStatus) error
	grpc.ServerStream
}

type dataProviderPingServer struct {
	grpc.ServerStream
}

func (x *dataProviderPingServer) Send(m *ServerStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _DataProvider_GetAdapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterHead)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProviderServer).GetAdapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoadapter.DataProvider/GetAdapter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProviderServer).GetAdapter(ctx, req.(*AdapterHead))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataProvider_ListAdapters_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Node)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataProviderServer).ListAdapters(m, &dataProviderListAdaptersServer{stream})
}

type DataProvider_ListAdaptersServer interface {
	Send(*Adapter) error
	grpc.ServerStream
}

type dataProviderListAdaptersServer struct {
	grpc.ServerStream
}

func (x *dataProviderListAdaptersServer) Send(m *Adapter) error {
	return x.ServerStream.SendMsg(m)
}

// DataProvider_ServiceDesc is the grpc.ServiceDesc for DataProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoadapter.DataProvider",
	HandlerType: (*DataProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdapter",
			Handler:    _DataProvider_GetAdapter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ping",
			Handler:       _DataProvider_Ping_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListAdapters",
			Handler:       _DataProvider_ListAdapters_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data-provider/protoadapter/adapter.proto",
}
