name: 'Build Node & Data Provider'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  data-provider-unit-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        run: echo Build!