name: Build Docker images
on:
  push:
    branches: ["ci-cd"]

env:
  REGISTRY: ${{ secrets.REGISTRY_URL }}
  IMAGE_NAME: ${{ github.repository }}
  NODE_IMAGE: ${{ github.repository }}/node
  DP_IMAGE: ${{ github.repository }}/data-provider
  NODE_PORT: 50051
  DP_PORT: 50052

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Nyx infer
        id: nyx
        uses: mooltiverse/nyx/github-action@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NYX_VERBOSITY: DEBUG
        with:
          dryRun: true

      - name: Print version
        run: echo the inferred version is ${{ steps.nyx.outputs.version }}


      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Node Docker images
        uses: docker/build-push-action@v4
        with:
          file: node.Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.NODE_IMAGE }}
          build-args: |
            PORT=${{ env.NODE_PORT }}


      - name: Build and push Data provider Docker images
        uses: docker/build-push-action@v4
        with:
          file: dp.Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.DP_IMAGE }}
          build-args: |
            PORT=${{ env.DP_PORT }}


