name: Build Docker images

on:
  push:
    branches: ["ci-cd"]
      # - development
      # - staging
      # - main

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: gitea.in.olakunleoladimeji.com
  NODE_IMAGE: ${{ format('{0}/{1}/node', vars, github.repository) }}
  DP_IMAGE: ${{ format('{0}/{1}/data-provider', github.server_url, github.repository) }}
  NODE_PORT: 50051
  DP_PORT: 50052

jobs:
  build-docker-images:
      
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Nyx infer
      #   id: nyx
      #   uses: mooltiverse/nyx-github-action@main
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NYX_VERBOSITY: DEBUG
      #   with:
      #     dryRun: true

      # - name: Print version
      #   run: echo the inferred version is ${{ steps.nyx.outputs.version }}


      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          logout: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - 
        name: Dump current vars
        run: echo '${{ toJSON(github) }}'

      - name: Build and push Node Docker images
        uses: docker/build-push-action@v4
        with:
          file: node.Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/node
          build-args: |
            PORT=${{ env.NODE_PORT }}


      # - name: Build and push Data provider Docker images
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: dp.Dockerfile
      #     context: .
      #     push: true
      #     tags: |
      #       ${{ env.DP_IMAGE }}
      #     build-args: |
      #       PORT=${{ env.DP_PORT }}
