name: Build Docker images
on:
  push:
    branches: ["development"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ gitea.repository }}
  NODE_IMAGE: ${{ gitea.repository }}/node
  DP_IMAGE: ${{ gitea.repository }}/data-provider
  NODE_PORT: 50051
  DP_PORT: 50052

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Node Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          file: node.Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.NODE_IMAGE }}
          build-args: |
            PORT=${{ env.NODE_PORT }}


      - name: Build and push Data provider Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          file: dp.Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.DP_IMAGE }}
          build-args: |
            PORT=${{ env.DP_PORT }}


