name: Go unit test provider & node
on:
  push:
    branches: ["wip-*", "feature-*", "hot-fix-*"]
  pull_request:
    branches: ["main", "stage", "development"]

jobs:
  test-go:
    strategy:
      matrix:
        go: [1.18, 1.19]
        directory: ["node", "data-provider"]
    runs-on: ubuntu-latest
    steps:
      - name: Setup branch
        uses: actions/checkout@v3

      - name: Setup go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go }}
      - name: Running Test For ${{ matrix.directory }}
        run: COCKROACH_DNS_URL=${{ secrets.COCKROACH_DNS_URL }} NODE_URL_WSS=${{ secrets.NODE_URL_WSS }} NODE_URL_HTTPS=${{ secrets.NODE_URL_HTTPS }} PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} X_COIN_API_KEY=${{ secrets.PRIVATE_KEY }} go test -v ./...
        working-directory: ${{ matrix.directory }}