# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '22 22 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.github_token }}
        stale-issue-message: 'Stale issue closing. You can re-open this issue again if this was a mistake'
        stale-pr-message: 'Stale pull request closing. You can re-open this PR again if this was a mistake'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
